const server = import.meta.env.VITE_SERVER

const  NEW_MESSAGE = "NEW_MESSAGE"
const  NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT"
const START_TYPING = "START_TYPING"
const STOP_TYPING = "STOP_TYPING"
const CHAT_LEAVED = "CHAT_LEAVED"
const CHAT_JOINED = "CHAT_JOINED"
const ONLINE_USERS = "ONLINE_USERS"
const REFETCH_CHATS = "REFETCH_CHATS"
const NEW_REQUEST = "NEW_REQUEST"
const ALERT = "ALERT"

export {server , ONLINE_USERS , NEW_MESSAGE , NEW_MESSAGE_ALERT ,  START_TYPING , STOP_TYPING , CHAT_JOINED , CHAT_LEAVED , NEW_REQUEST , REFETCH_CHATS , ALERT}